development:
  adapter: postgresql
  encoding: unicode
  username: marcandria
  database: scacchi
  password: frousht
  host: localhost
  pool: 5

  production:
    adapter: postgresql
    encoding: unicode
